# tokens-secrets.yml
name: Set GitHub Token Secret
on:
  push:
    branches:
      - main # or any other branch you want your app deployed from
jobs:
  set-token:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set GitHub token secret (if needed)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        echo ::env(MY_TOKEN) > .github/secrets/token.txt
