name: Deploy via SSH

on:
  push:
    branches:
      - main # Change this branch if needed, e.g., 'main', 'master'
  schedule:
    - cron: "0 12 * * *" # Schedule deployment at noon UTC every day

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
      
    - name: Install dependencies and generate Jekyll site
      run: |
        npm install
        npx jekyll build --config _config.yml

    - name: Deploy via SSH
      if: ${{ (github.ref == 'refs/heads/main' && github.event_name == 'push') || (github.event_name == 'schedule') }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.MY_TOKEN }} # Update the token secret name from GITHUB_TOKEN to MY_TOKEN
        publish_dir: ./_site # Directory containing the generated site files
